export { default as authService } from './authService'
export { default as patientService } from './patientService'
export { default as doctorService } from './doctorService'
export { default as reportService } from './reportService'
export { default as prescriptionService } from './prescriptionService'
export { default as aiService } from './aiService'
export { default as emergencyService } from './emergencyService'
